# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e587337821d40ca8a2f201eb52fa39e3e9f3b9d47df9e15e2199ef70e6eabaad36a8f38bf76efadfde70ef8ab128c5bdff4a7dbc812dd684b2d6492f86d9876a

test:
  secret_key_base: 4fcad1ca336b6c2fefb3593c7dbee544851109447375ed1e04d2cff572d550a7974d2b5459b5badc140f448d3016b602de6583f5ea87896a0fe0501a6bab0730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
